### ISSUE TITLE
паузы при отправке писем

### ISSUE THREAD

**Issue by ahl1982** [sazanof/EASYNEWSLETTER#1]
на некоторых хостингах, блокируется возможность отправки большого кол-ва писем, хорошо было бы сделать паузы при отправке или отправлять письма небольшими блоками по 10-20 писем. Хорошо было бы добавить возможность настраивать эти параметры. Так же можно добавить функцию выбора в категории, писем которые не были отправлены в последний раз.

**Comment by sazanof** [comment]
Реализовано в новой версии https://sazanof.ru/veb-razrabotka/modx-letters-modul-podpiski-i-rassylki.html
