### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by fourroses666** [sazanof/EASYNEWSLETTER#12]
Hi Sazanof,

I wonder what your plans are on EasyNewsletter.

For me it is very important to be able to send HTML mails with the option to select a Template. I normally use TEMailer for sending Mailings. It has some nice features.
Below here I will show you what features TEMailer has so you might get some good ideas.
1. Use Resources to send Mailings
2. Select resource to send
3. assign a subscribers group
4. list of all subscribers, show unsubscribed, group number / id, sortable
5. list of group to send to

![mailingmanager](https://f.cloud.github.com/assets/523389/2259590/bd6f2a8a-9e36-11e3-8003-91e3453b74e2.jpg)

---

Привет Sazanof,

Интересно, какие у вас планы на EasyNewsletter.

Для меня это очень важно, чтобы иметь возможность отправлять HTML письма с возможностью выбора шаблона. Я обычно использую TEMailer для отправки рассылок. Он имеет некоторые интересные особенности.
Ниже здесь я покажу вам, какие функции TEMailer имеет, так что вы можете получить некоторые хорошие идеи.
1. Используйте ресурсы для отправки Вам
2. Выберите ресурс для отправки
3. назначить абонентской группы
4. список всех абонентов, показать отписался, группы / ID, сортировке
5. Список группы для отправки

![mailingmanager](https://f.cloud.github.com/assets/523389/2259590/bd6f2a8a-9e36-11e3-8003-91e3453b74e2.jpg)

**Comment by sazanof** [comment]
https://sazanof.ru/veb-razrabotka/modx-letters-modul-podpiski-i-rassylki.html
https://github.com/sazanof/MODxLetters
See this! 

-Use Resources to send Mailings
-Select resource to send assign a subscribers group
-list of group to send to
