### ISSUE TITLE
Добавление футера к письму

### ISSUE THREAD

**Issue by lexwrlk** [sazanof/EASYNEWSLETTER#13]
Можно ли добавить футер (для ссылки на страницу с отпиской) к письму как чанк который будет устанавливаться в конфигурации модуля.
Сейчас я использую такой код (147 строка в backend.php):

<pre>
                        $footer = 1;
                        $footer_chunk = "mail-footer";
                        if ($footer) {
                                $footer_text = $modx->getChunk($footer_chunk);
                                $newsletter_newsletter = $newsletter_newsletter . "&lt;br&gt;" . $footer_text;
                        }
</pre>

Таким образом к письму добавляется содержимое чанка "mail-footer"

**Comment by sazanof** [comment]
https://github.com/sazanof/MODxLetters
https://sazanof.ru/veb-razrabotka/modx-letters-modul-podpiski-i-rassylki.html
Шаблонизация реализована в новой версии
